apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - image: mohitjurani/calculator:latest
      name: nodewebapp
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
